/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Machine.Pila;
import Machine.VirtualMachine;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author neON
 */
public class Interfaz extends javax.swing.JFrame {

    VirtualMachine VM ;
    DefaultTableModel modelo;
    JTextPane panel= new JTextPane();
    codigo_3.Codigo3 c3=new codigo_3.Codigo3();
    int contador =1;
    String []s= new String[1000];
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.VM = new VirtualMachine();
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");                                                                             
        this.jTable.setModel(modelo);
        

        //prueba
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRunc3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRunCompleto = new javax.swing.JTextArea();
        btnAbrir = new javax.swing.JButton();
        btnContador = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        labelArchivo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPanel = new javax.swing.JTextPane();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        jMenuItem1.setText("Menu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaRunc3.setColumns(20);
        txaRunc3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txaRunc3.setRows(5);
        jScrollPane1.setViewportView(txaRunc3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 304, 471));

        txaRunCompleto.setEditable(false);
        txaRunCompleto.setColumns(20);
        txaRunCompleto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txaRunCompleto.setForeground(new java.awt.Color(51, 51, 255));
        txaRunCompleto.setRows(5);
        txaRunCompleto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txaRunCompleto.setCaretColor(new java.awt.Color(60, 63, 65));
        jScrollPane2.setViewportView(txaRunCompleto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 295, 471));

        btnAbrir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setBorder(null);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));

        btnContador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContador.setText("Paso a paso");
        btnContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.setFillsViewportHeight(true);
        jTable.setShowGrid(true);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 364, 360, 230));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Archivo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 80, 30));

        labelArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelArchivo.setForeground(new java.awt.Color(255, 255, 255));
        labelArchivo.setAutoscrolls(true);
        getContentPane().add(labelArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 223, 22));

        txtPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPanel.setDoubleBuffered(true);
        txtPanel.setDragEnabled(true);
        jScrollPane4.setViewportView(txtPanel);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 370, 197));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, 20));

        jButton1.setText("Automatico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondo.jpg"))); // NOI18N
        jLabelFondo.setMaximumSize(new java.awt.Dimension(1100, 650));
        jLabelFondo.setMinimumSize(new java.awt.Dimension(1100, 650));
        jLabelFondo.setPreferredSize(new java.awt.Dimension(1100, 650));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // Codigo de btnAbrir:
        VM=new VirtualMachine();
        JFileChooser j = new JFileChooser();
        int option  = j.showOpenDialog(j);
        if (option == JFileChooser.APPROVE_OPTION){
            File file = j.getSelectedFile();
            String name = file.getName();
            int r = VM.open(name);
        
            if (r == VirtualMachine.ERRORarchivo){
                JOptionPane.showMessageDialog(null, 
                              "No se pudo cargar el archivo", 
                              "TITLE", 
                              JOptionPane.WARNING_MESSAGE);
                //System.err.println("No se pudo cargar el archivo ");
                VM=new VirtualMachine();
            }
        //VM.IP=-1;
        txaRunCompleto.setText("");
        txaRunc3.setText("");
        txtPanel.setText("");
        VM.sInterfaz="";
//        for (int i=0;i<contador;i++){
//            modelo.removeRow(0);
//            
//        }
        //contador=1;
        
        txaRunCompleto.setText(VM.c3.toString());
        labelArchivo.setText(name);

        }
        
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContadorActionPerformed
        // Codigo de btnContador:
        
        String []info = new String[1];
        Font fuente=new Font("Arial", Font.ITALIC, 15);
        VM.runPasoPaso();
        int ip = VM.IP;

        String line = VM.c3.getLinea(ip);
        String tx = txaRunc3.getText();
        
        info[0] = line;
        s[contador-1]=line;     
        txaRunc3.setText( tx+line);
        
        contador++;
        modelo.addRow(info);
        Random randomGenerator = new Random();
        int red = randomGenerator.nextInt(256);
        int green = randomGenerator.nextInt(256);
        int blue = randomGenerator.nextInt(256);
        
        txtPanel.setText(VM.sInterfaz);
        Color randomColour = new Color(red,green,blue);
        //this.jTable.setBackground(randomColour);
        this.jTable.setRowHeight(25);

       
        
        //ontador++;
    }//GEN-LAST:event_btnContadorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VM.run();
        //String s = VM.sInterfaz;
        txtPanel.setText(VM.sInterfaz);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnContador;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel labelArchivo;
    private javax.swing.JTextArea txaRunCompleto;
    private javax.swing.JTextArea txaRunc3;
    private javax.swing.JTextPane txtPanel;
    // End of variables declaration//GEN-END:variables
}
